"""Muda coluna date para Date na tabela tickers

Revision ID: 53d7d9c25689
Revises: a8a6906fd292
Create Date: 2025-10-25 18:16:47.532730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d7d9c25689'
down_revision: Union[str, Sequence[str], None] = 'a8a6906fd292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
